name: Generate Datas

on:
  schedule: 
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

permissions: 
  contents: write  # ✅ Grant write permission to GITHUB_TOKEN

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git User
        run: |
          git config --global user.name "RamKrishna7410"
          git config --global user.email "ranitmanik555@gmail.com"

      - name: Generate Snake Animation
        uses: Platane/snk@v3.2.0
        id: snake-gif
        with:
          github_user_name: RamKrishna7410
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
